### ISSUE TITLE
Admin UI

### ISSUE THREAD

**Issue by dknx01** [MarlonSchultz/jeopardy#4]
An admin ui for adding, editing or delete new questions/answers

**Comment by MarlonSchultz** [comment]
I am going to skip tests on DI and stuff like that, since you are heavily editing those.

One question tho. Can you see what Travis is complaining about if a build fails ?

**Comment by MarlonSchultz** [comment]
We could use order by rand(). Guess the db wont get too fat to worry about perfomance in this case.
