### ISSUE TITLE
We need some tests

### ISSUE THREAD

**Issue by dknx01** [MarlonSchultz/jeopardy#7]
Einige Klassen sollten wir dann auch noch kurz Unit-Testen. Eventuell könnte man funktionale Tests (Codeception oder so) schreiben

**Comment by MarlonSchultz** [comment]
- Für das Model und die Collection werde ich das in PHPUnit abessen.
- Codeception kann status und mimetype prüfen. 
- Modale braucht glaube Selenium.
- Should we talk in english ?
