### ISSUE TITLE
Database should by a file storage

### ISSUE THREAD

**Issue by MarlonSchultz** [MarlonSchultz/jeopardy#9]
* Current state: Database is SQLite3.
* Should be: Flat file.

Editing the DB in SQLite3 is a hassle. If we store the question within a huge array / json  whatever, it would be easier to add and modify questions.

**Comment by dknx01** [comment]
Maybe not SHOULD, but CAN ALSO? so that you can use both.

**Comment by MarlonSchultz** [comment]
I see work.

Agreed.

**Comment by MarlonSchultz** [comment]
This is actually not as trivial as i initially thought.

The model uses PDO. SQLite3 is as flat as it gets when it comes to PDO DB File Storage. 

If the database class where to return some other kind of db connection, it should point to a different model. Perhaps an adapter for the model would be a solution. But thats a alot of trouble for something like this.

In retrospect it would b easier to actually drop SQLite3 all together and stick only to a flat file.

What do you say ?

**Comment by MarlonSchultz** [comment]
Oh, other idea. 

The flat file is read and then stored within a pdo:memory instance. This would make pdo still work and wouldn obstruct the implemantion of other db systems.

**Comment by dknx01** [comment]
pdo:memory sounds good. the config could be like:
`db_type: 'file'
db_path: 'PATH/TO/DB-FILE'
`
and I think there should be an interface for the file-db, so that we know how this one looks like. And then the file type could be different (json or php-array):

`db_type: 'file_json'
db_path: 'PATH/TO/DB.json'
`

`<?php
$db = json_decode(file_get_contens(db_path));
$checkJsonStructure();
`

**Comment by MarlonSchultz** [comment]
I wanted to use symfony/serializer.

Ive started writing an interface anyway. However, a huge drawback for me is: the factory would need to instantiate a new flatFileAdapter class and pass the serializer. This introduces implicit dependencies. 

Ill have another go at this problem tommorow.  Am going to push my current stuff in a couple of minutes.

**Comment by MarlonSchultz** [comment]
This one is done, will write tests for it as well.

Solution is prety simple in the end. Reads json and puts it into a memory sqlite db. we can therefore still use the pdo wrapper. When the admin ui is finished we need to come up with a plan on how to write to the filesystem. But that shouldnt be to hard. Should be a json_encode thing.
